import React, { useContext, useState } from 'react'
import { MdSecurity } from 'react-icons/md'
import Link from 'next/link'
import Head from 'next/head'
import { VartaContext } from '../context/context'
import { AiOutlineLoading3Quarters } from 'react-icons/ai'
import ReCAPTCHA from 'react-google-recaptcha'

const Signup = () => {
  const { userSignup, alertError } = useContext(VartaContext)

  const [signingup, setSigningup] = useState(false)
  const [credentials, setCredentials] = useState({ username: '', name: '', email: '', password: '' })
  const [cpassword, setCpassword] = useState()
  const [gRecaptcha, setGRecaptcha] = useState('')

  const onChange = (e) => {
    setCredentials({ ...credentials, [e.target.name]: e.target.value })
  }
  const onChangeRecaptcha = (captchaValue) => {
    setGRecaptcha(captchaValue)
  }
  const onSubmit = async (e) => {
    e.preventDefault()
    setSigningup(true)
    if (gRecaptcha.length != 0) {
      credentials.password === cpassword ? await userSignup(credentials) : ""
    }
    else {
      alertError("Please verify the captcha!")
    }
    setSigningup(false)
    window.grecaptcha.reset();
  }

  return (
    <>
      <Head>
        <title>Varta | Signup</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/icons/discord.svg" />
      </Head>
      <div className="min-h-screen flex items-center justify-center px-4 sm:px-6">
        <div className={`max-w-md w-full space-y-3  mx-auto my-auto ${signingup ? 'pointer-events-none' : ''}`}>
          <div>
            <img
              className="mx-auto h-12 w-auto"
              src={`/icons/discord.svg`}
              alt="Workflow"
            />
            <h2 className="mt-6 text-center text-3xl font-extrabold text-gray-300">Create your account</h2>
          </div>
          <form onSubmit={onSubmit} className="mt-2 space-y-6" action="#" method="POST">
            <input type="hidden" name="remember" defaultValue="true" />
            <div className="shadow-sm -space-y-px">
              <div>
                <label htmlFor="name" className="sr-only">
                  Full name
                </label>
                <input
                  disabled={signingup}
                  onChange={onChange}
                  id="name"
                  name="name"
                  type="text"
                  required
                  className="rounded-lg w-full border-none outline-none p-3 h-11/12 resize-none text-white bg-gray-800 mb-2"
                  placeholder="Full name"
                />
              </div>
              <div>
                <label htmlFor="username" className="sr-only">
                  Username
                </label>
                <input
                  disabled={signingup}
                  onChange={onChange}
                  id="username"
                  name="username"
                  type="text"
                  required
                  className="rounded-lg w-full border-none outline-none p-3 h-11/12 resize-none text-white bg-gray-800 mb-2"
                  placeholder="Username"
                />
              </div>
              <div>
                <label htmlFor="email" className="sr-only">
                  Email address
                </label>
                <input
                  disabled={signingup}
                  onChange={onChange}
                  id="email"
                  name="email"
                  type="email"
                  required
                  className="rounded-lg w-full border-none outline-none p-3 h-11/12 resize-none text-white bg-gray-800 mb-2"
                  placeholder="Email address"
                />
              </div>
              <div>
                <label htmlFor="password" className="sr-only">
                  Password
                </label>
                <input
                  disabled={signingup}
                  onChange={onChange}
                  id="password"
                  name="password"
                  type="password"
                  required
                  minLength={6}
                  className="mb-2 rounded-lg w-full border-none outline-none p-3 h-11/12 resize-none text-white bg-gray-800"
                  placeholder="Password"
                />
              </div>
              <div>
                <label htmlFor="cpassword" className="sr-only">
                  Confirm password
                </label>
                <input
                  disabled={signingup}
                  onChange={(e) => { setCpassword(e.target.value) }}
                  id="cpassword"
                  name="cpassword"
                  type="cpassword"
                  required
                  minLength={6}
                  className="rounded-lg w-full border-none outline-none p-3 h-11/12 resize-none text-white bg-gray-800"
                  placeholder="Confirm password"
                />
              </div>
            </div>

            <div className="shadow-sm -space-y-px">
              <div className="relative w-full flex justify-center">
                <ReCAPTCHA
                  sitekey={process.env.NEXT_PUBLIC_RECAPTCHA_SITE_KEY}
                  onChange={onChangeRecaptcha}
                />
              </div>
            </div>

            <div className="flex items-center justify-between">
              <div className="flex items-center">
                <input
                  disabled={signingup}
                  onChange={() => { }}
                  id="remember-me"
                  name="remember-me"
                  type="checkbox"
                  checked
                  className="h-4 w-4 text-blue-600 focus:ring-blue-700 border-gray-300 rounded-lg"
                />
                <label htmlFor="remember-me" className="ml-2 block text-sm text-gray-300">
                  Remember me
                </label>
              </div>
            </div>

            <div>
              <button
                disabled={signingup}
                type="submit"
                className="group relative w-full flex justify-center py-2 px-4 border border-transparent text-sm font-medium rounded-md text-white bg-blue-600 hover:bg-blue-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500"
              >
                <span className="absolute left-0 inset-y-0 flex items-center pl-3">
                  <MdSecurity className="h-5 w-5 text-indigo-500 group-hover:text-indigo-400" size={24} />
                </span>
                {signingup ?
                  <AiOutlineLoading3Quarters className='animate-spin' size={24} />
                  :
                  'Create account'
                }
              </button>
            </div>
            <div className="text-sm flex justify-between">
              Already have an account?
              <Link href="/login">
                <a disabled={signingup} className="font-medium text-blue-600 hover:text-blue-700">
                  Login here
                </a>
              </Link>
            </div>
          </form>
        </div>
      </div>
    </>
  )
}

export default Signup